import University from "./University.mjs";
import User from "./User.mjs";
import Student from "./Student.mjs";
import Worker from "./Worker.mjs";

const lp = new University('National University LvivPolytechnic','Lviv',788000);
const lnu = new University('Lviv National University','Lviv',750055555);
const knu = new University('Kyiv National University', 'Kyiv', 844444444);
console.log('\n');
console.log(lp.getAddress());
console.log(lnu.getAddress());
console.log(knu.getAddress());
console.log('\n');

const user = new User('Misha','Savchak',1991);
console.log(user.getFullName());
console.log(user.getInfo());
console.log('\n');

const student1 = new Student('Misha','Savchak',1991,2014, lp) ;
console.log(student1.getCourse());
console.log(student1.isFinished());
console.log(Student.getCounter());
console.log(student1.getFullInfo());
const student2 = new Student('FirstName','LastName',1991,2019);
console.log('\n');
console.log(student2.getCourse());
console.log(student2.isFinished());
console.log(Student.getCounter());
console.log(student2.getFullName());
console.log(student2.getFullInfo());
console.log('\n');
const student3 = new Student('Markiyan', 'Pryima', 2002,2020, lnu);
console.log(student3.getCourse());
console.log(student3.isFinished());
console.log(Student.getCounter());
console.log(student3.getFullName());
console.log(student3.getFullInfo());
console.log('\n');

const worker = new Worker('Misha','Savchak',1991,20,34);
console.log(worker.getFullName());
console.log(worker.isRetired());
console.log(worker.getSalary());
console.log(worker.days);
console.log(worker.rate);
worker.retired = true;
console.log(worker.getSalary());
console.log('\n');
const worker2 = new Worker('Markiyan', 'Pryima', 2002, 30, 30);
console.log(worker2.getFullName());
console.log(worker2.isRetired());
console.log(worker2.getSalary());
console.log(worker2.days);
console.log(worker2.rate);
worker2.retired = true;
console.log(worker2.getSalary());
const worker3 = new Worker('FirstName', 'LastName', 2000, 20, 30, true);
console.log(worker3.getFullName());
console.log(worker3.isRetired());
console.log(worker3.getSalary());
console.log(worker3.days);
console.log(worker3.rate);
worker3.retired = false;
console.log(worker3.getSalary());